import type { Taal } from './types.js';
export const taals: readonly Taal[] = [
  {
    id: '7c7c6c57-17e5-4f98-960a-7170619237c2',
    name: 'Dadra',
    beats: 6,
    vibhag: [
      { beat: 1, value: 'X' },
      { beat: 4, value: '0' },
    ],
    notes: ['Dha', 'Dhin', 'Na', 'Dha', 'Tin', 'Na'],
  },
  {
    id: 'cb17fe44-14de-471f-a5b9-1c2181267d48',
    name: 'Teentaal',
    beats: 16,
    vibhag: [
      { beat: 1, value: 'X' },
      { beat: 5, value: '2' },
      { beat: 9, value: '0' },
      { beat: 13, value: '3' },
    ],
    notes: [
      'Dha',
      'Dhin',
      'Dhin',
      'Dha',
      'Dha',
      'Dhin',
      'Dhin',
      'Dha',
      'Dha',
      'Tin',
      'Tin',
      'Ta',
      'Ta',
      'Dhin',
      'Dhin',
      'Dha',
    ],
  },
  {
    id: 'c1e4ad52-2d04-4502-abd6-fbc6b8b8224e',
    name: 'Jhaptal',
    beats: 10,
    vibhag: [
      { beat: 1, value: 'X' },
      { beat: 3, value: '2' },
      { beat: 6, value: '0' },
      { beat: 8, value: '3' },
    ],
    notes: [
      'Dhin',
      'Na',
      'Dhin',
      'Dhin',
      'Na',
      'Tin',
      'Na',
      'Dhin',
      'Dhin',
      'Na',
    ],
  },
  {
    id: 'b41711d2-22a9-444b-8ae2-ba51644c9483',
    name: 'Rupak',
    beats: 7,
    vibhag: [
      { beat: 1, value: 'X' },
      { beat: 4, value: '2' },
      { beat: 6, value: '3' },
    ],
    notes: ['Tin', 'Tin', 'Na', 'Dhin', 'Na', 'Dhin', 'Na'],
  },
  {
    id: '1f1253c2-5315-4155-bacf-f78bb951296b',
    name: 'Keherwa',
    beats: 8,
    vibhag: [
      { beat: 1, value: 'X' },
      { beat: 5, value: '0' },
    ],
    notes: ['Dha', 'Ge', 'Na', 'Ti', 'Na', 'Ka', 'Dhin', 'Na'],
  },
  {
    id: 'f2514480-f077-48c3-8955-37c22c65c3cd',
    name: 'Ektaal',
    beats: 12,
    vibhag: [
      { beat: 1, value: 'X' },
      { beat: 3, value: '0' },
      { beat: 5, value: '2' },
      { beat: 7, value: '0' },
      { beat: 9, value: '3' },
      { beat: 11, value: '4' },
    ],
    notes: [
      'Dhin',
      'Dhin',
      'Dha Ge',
      'Tit',
      'Tu',
      'Na',
      'Ka',
      'Ta',
      'Dha Ge',
      'Tit',
      'Tu',
      'Na',
    ],
  },
  {
    id: 'd57e31ad-7a9a-4cf4-9ead-f89cf5509bab',
    name: 'Deepchandi',
    beats: 14,
    vibhag: [
      { beat: 1, value: 'X' },
      { beat: 4, value: '2' },
      { beat: 8, value: '0' },
      { beat: 11, value: '3' },
    ],
  },
  {
    id: '6efd2ea7-39d8-4224-8652-e1fbadbe67f4',
    name: 'Tilwada',
    beats: 16,
    vibhag: [
      { beat: 1, value: 'X' },
      { beat: 5, value: '2' },
      { beat: 9, value: '0' },
      { beat: 13, value: '3' },
    ],
  },
  {
    id: '827e9dda-ab5c-4509-bf86-00c18149fbb8',
    name: 'Jhoomra',
    beats: 14,
    vibhag: [
      { beat: 1, value: 'X' },
      { beat: 4, value: '2' },
      { beat: 8, value: '0' },
      { beat: 11, value: '3' },
    ],
  },
  {
    id: 'f3a9b1c8-6e2d-4f7a-8b1e-9c0d5a4f6b7e',
    name: 'Farodast',
    beats: 14,
    vibhag: [
      { beat: 1, value: 'X' },
      { beat: 3, value: '0' },
      { beat: 5, value: '2' },
      { beat: 7, value: '0' },
      { beat: 9, value: '3' },
      { beat: 12, value: '4' },
    ],
  },
  {
    id: 'e7f6a5b4-c3d2-1e9f-a8b7-0c9d8e7f6a5b',
    name: 'Mahesh Taal',
    beats: 9,
    vibhag: [
      { beat: 1, value: 'X' },
      { beat: 5, value: '2' },
      { beat: 7, value: '3' },
    ],
  },
  {
    id: 'b5e4a3f2-1c8d-4e7b-9a1f-0d9c8e7f6a5b',
    name: 'Chartal Ki Savari',
    beats: 11,
    vibhag: [
      { beat: 1, value: 'X' },
      { beat: 5, value: '2' },
      { beat: 7, value: '3' },
      { beat: 9, value: '4' },
    ],
  },
  {
    id: 'c9f8e7d6-a5b4-3c2d-1e9f-a8b70c9d8e7f',
    name: 'Ada Chautal',
    beats: 14,
    vibhag: [
      { beat: 1, value: 'X' },
      { beat: 3, value: '2' },
      { beat: 5, value: '0' },
      { beat: 7, value: '3' },
      { beat: 9, value: '0' },
      { beat: 11, value: '4' },
      { beat: 13, value: '0' },
    ],
  },
  {
    id: 'd2e1f0c9-a8b7-4e6f-9c1d-0e9f8a7b6c5d',
    name: 'Jagpal Taal',
    beats: 11,
    vibhag: [
      { beat: 1, value: 'X' },
      { beat: 6, value: '2' },
      { beat: 8, value: '4' },
      { beat: 10, value: '4' },
    ],
  },
];